### ISSUE TITLE
Would you accept a PR for automatic script building?

### ISSUE THREAD

**Issue by 0b1kn00b** [NQNStudios/kisslang#143]
@back2dos has a library [here](https://github.com/haxetink/tink_syntaxhub) that's pretty straightforward. Would obviate the need for `.hx` files. Here's one of the examples.

```haxe
import tink.syntaxhub.*;
import haxe.macro.Expr;
import haxe.macro.Context;

class TxtFrontend implements FrontendPlugin {
	
	public function new() {}
	
	public function extensions() 
		return ['txt'].iterator();
	
	public function parse(file:String, context:FrontendContext):Void {
		
		var text = sys.io.File.getContent(file);
		var pos = Context.makePosition({ file: file, min: 0, max: text.length });
		
		context.getType().fields.push({
			name: 'TEXT',
			access: [AStatic, APublic],
			kind: FProp('default', 'null', macro : String, macro $v{text}),
			pos: pos,
		});
	}
	static function use()
		tink.SyntaxHub.frontends.whenever(new TxtFrontend());
}
```

**Comment by NQNStudios** [comment]
I would be interested in this. I am available to remotely pair program this change if you would like, between 10 AM and 5 PM Mountain time on week days.

Assuming the library is straightforward, it's still a major change that could run into fundamental limitations with how Kiss is structured. I'll get into the reasons, and offer a workaround.

There are two significant reasons .hx files have always been required:

## import statements.
 I'm only aware of two ways to import packages via a macro:
   *  [Context.defineModule()](https://api.haxe.org/haxe/macro/Context.html#defineModule). I remember reading somewhere that this function is only available in initialization macros, not build macros, although now I can't find that anywhere so I could be mistaken.
   *  [Compiler.include()](https://api.haxe.org/haxe/macro/Compiler.html#include). As above, I was under the impression this could not be used in a build macro, because haxe.macro.Compiler docs state "these methods can be called for compiler configuration macros" (which are the same thing as initialization macros, right?) The docs for this function only mention being able to import modules from the classPlath, not from haxelib dependencies. If the classpaths of every haxelib can be obtained at macro time and passed to `include()`, that could be worked around. If not, `Context.defineModule()` would be the only way to supply import statements from a Kiss file. But I always wanted to be able to mix and match haxe functions with Kiss functions, which is why I wanted to keep Kiss based on a build macro instead of constructing a TypeDefinition object for `defineModule()`.

I see that the FrontendContext class that tink_syntaxhub builds onto, provides `addImport()` and `addUsing()`, which may be the best way to handle this.

## typedefs

I decided it was a poor use of time to implement a kiss-based syntax for typedefs, when I could just put typedefs in the .hx file. I've never needed to use a macro to generate a typedef, which is the only reason I can think of for implementing a typedef creation system for Kiss.

I would not be interested in adding a typedef creation system and having to maintain it. So, this PR would need to be backwards-compatible with the old way of including a `.hx` file that calls `Kiss.build()`. I believe that is possible, because the docs say front ends are applied via Context.onTypeNotFound() -- so if a `.hx` file is present, I'm assuming the frontend wouldn't be triggered. So the trick would be to have the frontend call `Kiss.build()` and put those fields onto the FrontEndContext's type, and that way I continue to expand Kiss via the same `Kiss.build()` function that has always provided the core functionality.

## workaround

I will also say that I've worked around the annoyance of separate .hx files, by automating their creation via the `kiss-vscode` extension. If you use VSCode, I can help you get the extension installed, and you can use it to generate the `.hx` and `.kiss` files for new classes. It also provides a shortcut for switching between the two. That's a big reason why keeping `.hx` files around has been acceptable to me.

Let me know if anything here needs clarification. :)

**Comment by NQNStudios** [comment]
Also, I will need to make all the CI tests pass before I can evaluate any incoming PRs. I'll try to do it today if it doesn't take too long.

**Comment by 0b1kn00b** [comment]
I'll get my head around the test setup for next week.

**Comment by NQNStudios** [comment]
I made a branch to base this feature on, [no-hx-files](https://github.com/NQNStudios/kisslang/tree/no-hx-files).

I'll be working on dev branch and probably breaking things this week.

**Comment by NQNStudios** [comment]
- [x] What package namespace do the generated classes end up in? It seems to be the equivalent of a `package;` at the top of the file? I would rather it match the project name and subdirectory, so instead of `import LeetCode;` we have `import smooch.LeetCode;`.
- [ ] ~~Can the main class of a project be declared without a haxe file?~~ Sadly this results in `Invalid -main : smooch.Main is not a class`
- [x] Add `(import <type>)` and `(using <type>`) supporting all import and using types
- [x] Would it be overreaching to make some common imports (i.e. `using StringTools;` or `import haxe.ds.Option`) automatic for classes defined this way?
- [x] Can a kiss-only class import another kiss-only class?
- [x] Does it remain possible to split Kiss classes into multiple files using `(load <file>)` expressions?
- [x] Can the FrontEnd be made to run by default for any project that uses `-lib kiss`?
- [ ] ~~Through a new macro or special form, can EmbeddedScript/AsyncEmbeddedScript dsl formats be declared with their own custom extensions?~~ Making a separate issue
- [x] Can special forms be provided to allow .kiss files to use `extends` and `implements`?

**Comment by NQNStudios** [comment]
I'm not assigning you this big checklist--I'm going to work on it myself but feel free to dive in as well with more pull requests.

**Comment by 0b1kn00b** [comment]
Behind the scenes it's doing `Context.defineModule` so using `using` is a case of opening up the api, and you might maintain a fork of tink_syntaxhub for that.

Anything that is failing regards searching for implementations is sitting on the `Context.onTypeNotFound` handler so it's supported by the compiler team. Main and .kiss interdependencies should run through that path.

I think the package/module is derived from the filename/classpath. The FrontendContext exposes the field array and not much else afaik.

If you use the tink macro with the KissFrontend in the `extraParams.hxml` in the way I've specified your boot code there, it'll run automatically on any project that uses the library.

If you base your architecture on the tink library, you could forward any of the FrontendContext for use in special forms/ macros through the state object, although the frontend interface has to be specified external to that because a filter is run on the extension patterns before any file is loaded.

**Comment by NQNStudios** [comment]
> Behind the scenes it's doing `Context.defineModule` so using `using` is a case of opening up the api, and you might maintain a fork of tink_syntaxhub for that.

I don't think that's necessary. FrontendContext provides `addUsing()` and `addImport()`, so I'm gonna try using those. Forking a tink library would be outside the scope for this project.

**Comment by NQNStudios** [comment]
I've implemented the tests and additional features I wanted. Now in a frontend-based class, you can `(import <Types...>)`, `(importAs <Type> <Alias>)`, `(importAll <package>)`, `(using <Types...>)`, `(extends <SuperClass>)`, or `(implements <Interfaces...>)`.

I'm very happy with this. I'm going to remove the smooch project because I now have more comprehensive tests for it that get called through BasicTestCase, and if all the tests pass I will merge it with `dev`. Thanks for this contribution!
