### ISSUE TITLE
Running `test-project` yields the following.

### ISSUE THREAD

**Issue by 0b1kn00b** [NQNStudios/kisslang#145]
```bash
⋊> ~/i/l/h/k/git on dev ◦ ./test-project.sh                                                                             11:33:09
Development directory set to /mnt/dat/lib/haxe/kiss/git/kiss
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/asciilib
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/bump-version
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/hollywoo
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/hollywoo-flixel
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/kiss-express
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/kiss-flixel
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/kiss-tools
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/kiss-vscode
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/leet-code
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/lets-read
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/nat-archive-tool
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/prokgen
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/re-flex
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/requests-externs
Development directory set to /mnt/dat/lib/haxe/kiss/git/projects/sched
Installing all libraries from /mnt/dat/lib/haxe/kiss/git/projects/aoc/build.hxml:
Loading info about the required libraries
Haxelib is going to install these libraries:
  kiss - 0.0.1
Downloading kiss-0,0,1.zip...
Installing kiss...
  Current version is now 0.0.1
Done
Installing dependency hscript 2.5.0
Library hscript version 2.5.0 is already installed
Installing dependency tink_json 0.11.0
Library tink_json version 0.11.0 is already installed
Installing dependency tink_macro 1.0.0
Library tink_macro version 1.0.0 is already installed
Installing dependency haxe-strings 7.0.2
Library haxe-strings version 7.0.2 is already installed
Installing dependency uuid 2.4.1
Library uuid version 2.4.1 is already installed
-D day1 -D day2 -D day3 -D day4 -D day5 -D day6 -D day7 -D day8 -D day9 -D day10 -D day11 -D day12 -D day13 -D day14 -D day15 -D day16 -D day17 -D day18 -D day19 -D day20 -D day21 -D day22 -D day23 -D day24 -D day25 -D year2018 -D year2019 -D year2020 -D year2021
src/year2021/Solutions2021.kiss:23:58: Kiss compilation failed: macro-time hscript parsing failed with EUnexpected(s):
{
        {
                final s = Stream.fromFile(eval(file)), commands = [];
                {
                        while (!Prelude.truthy(s.isEmpty())) {
                                s.isEmpty();
                                commands.push(b.call(read(s), [read(s)]));
                                s.dropWhitespace();
                        };
                        {
                                Helpers.evalUnquotes({ pos : { column : 10, line : 7, absoluteChar : 236, file : "src/year2021/day2.kiss" }, def : kiss.ReaderExp.ReaderExpDef.CallExp({ pos : { column : 11, line : 7, absoluteChar : 237, file : "src/year2021/day2.kiss" }, def : kiss.ReaderExp.ReaderExpDef.Symbol("lambda") }, [{ pos : { column : 18, line : 7, absoluteChar : 244, file : "src/year2021/day2.kiss" }, def : kiss.ReaderExp.ReaderExpDef.ListExp([]) }, { pos : { column : 21, line : 7, absoluteChar : 247, file : "src/year2021/day2.kiss" }, def : kiss.ReaderExp.ReaderExpDef.Unquote({ pos : { column : 22, line : 7, absoluteChar : 248, file : "src/year2021/day2.kiss" }, def : kiss.ReaderExp.ReaderExpDef.CallExp({ pos : { column : 23, line : 7, absoluteChar : 249, file : "src/year2021/day2.kiss" }, def : kiss.ReaderExp.ReaderExpDef.Symbol("b.begin") }, [{ pos : { column : 31, line : 7, absoluteChar : 257, file : "src/year2021/day2.kiss" }, def : kiss.ReaderExp.ReaderExpDef.Symbol("commands") }]) }) }]) }).def;
                        };
                };
        };
}
From:[(begin (let [s (Stream.fromFile (eval file)) commands []] (until (s.isEmpty) (commands.push (b.call (read s) [(read s)])) (s.dropWhitespace)) `(lambda [] ,(b.begin commands))))]
```

**Comment by NQNStudios** [comment]
Can you verify that you've checked out the most recent commit, 8de1aa342dde73b2b195f47a339213267ac906ab on the dev branch?

**Comment by 0b1kn00b** [comment]
currently on head at 45f1e83a61ddabefe6d828ea8e5aa7c0d3f05594. ubuntu 22.04, if that could be relevant

**Comment by NQNStudios** [comment]
Can you send me the output of `haxelib list`?

Here's some explanation on how the tests work, which might explain why this isn't working (or it might not)!

When GitHub Actions runs a test, it starts with either KISS_TARGET or KISS_PROJECT set as an environment variable, and runs test.sh.

When KISS_TARGET it set, it runs core unit tests of Kiss functionality when compiled into the given haxe target (py, js, cs, etc.).

When KISS_PROJECT is set, it looks into the `projects` folder for the given project, and tests it. This involves figuring out what kind of project it is, whether it defines its own test process, and trying to install the right dependencies.

So while `test-project` might sound like it is the entry point for testing the kisslang project, it's actually a script for testing an individual sub-project of Kisslang. When called without args or environment variables, it tests `aoc`, which is my Advent of Code solutions from past years. That's where this failure is happening.

My current theory is that it's failing for you because when you run the test scripts locally, one step in `test.sh` is skipped.

```
# If Travis is running tests, basic dependencies need to be installed
if [ ! -z "$CI_OS_NAME" ]
then
    (cd kiss/build-scripts && haxelib install all --always --quiet)
    (cd kiss/build-scripts/$KISS_TARGET && haxelib install all --always --quiet)
fi
```

The comment there is outdated -- GitHub Actions runs the tests now.

But possibly if you run 
```
(cd kiss/build-scripts && haxelib install all --always --quiet)
(cd kiss/build-scripts/interp && haxelib install all --always --quiet)
```
it will fix the `aoc` test failure.

Sorry if you had already worked this flow out and I'm re-explaining. Once we solve this issue I will wrap this explanation into a CONTRIBUTING.md file so future contributors can run tests locally without the same hassle.

**Comment by 0b1kn00b** [comment]
Ok, so I'm calling this incorrectly.

**Comment by NQNStudios** [comment]
Yes and no. It's valid to call `test-project.sh` directly when you want to test one of the projects locally, and all testable projects should succeed if your dependencies are in order. So this failure of the `aoc` project does interest me. Were you able to update dependencies and run the script successfully?

Right now there is no easy script for locally running every possible test. Since I've been working alone for a while, I am careless about it and I let GitHub Actions catch errors after I push them to dev. Then, once a month or less, I fix those errors. I haven't concerned myself with keeping a stable `main` branch or releases to haxelib.

If you are serious about using/contributing to Kisslang, I'll have to tighten things up to maintain a stable branch. But you should know it will never be as stable or well-maintained as Haxe or any of Haxe's target languages. (i.e. if something happens to me, the project will be dead.)
